services:
  httpd:
    image: httpd:2.4-alpine
    container_name: meshing-viewer
    ports:
      - "8080:80"
    volumes:
      - ./webapp/dist:/usr/local/apache2/htdocs/
    restart: unless-stopped
